[package]
name = "ljp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
include_dir = "0.7.4"
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
